version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
   interval: "weekly"
  labels:
    - "dependencies"
    - "ok-to-test"
  open-pull-requests-limit: 20
- package-ecosystem: gomod
  directory: "/"
  schedule:
   interval: "daily"
  filter:
    - name: "github.com/openshift/osde2e-common"
  labels:
    - "dependencies"
    - "ok-to-test"
  open-pull-requests-limit: 1
